spring:
  application:
    name: access
  datasource:
    url: jdbc:postgresql://localhost:5434/lms
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083